In [2]:
import pandas as pd

data_dir = "./../data/"

In [4]:
biotoxins_ts = pd.read_excel(data_dir + 'biotoxins_preprocessed.xlsx', index_col='Date', parse_dates=True,
                             engine="openpyxl")
biotoxins_ts

,Sample,Species,Sample_Point,Production_Area,dsp_toxins,asp_toxins,psp_toxins
Date,,,,,,,
2015-01-05,1,Mexilhão,Jangada,LAL,20.0,1.8,71.0
2015-01-05,20,Berbigão,Canal do Espinheiro,RIAV3,36.0,1.8,71.0
2015-01-05,19,Berbigão,Costa Nova,RIAV2,26.0,1.8,71.0
2015-01-05,18,Berbigão,Moacha,RIAV1,36.0,1.8,71.0
2015-01-05,17,Amêijoa-branca,Torreira,L3,36.0,1.8,71.0
...,...,...,...,...,...,...,...
2020-12-29,2211,Mexilhão,Povoação,POR2,36.0,1.8,NaN
2020-12-29,2212,Mexilhão,Aljezur,L7a,36.0,NaN,NaN
2020-12-29,2213,Mexilhão,Garganta,OLH4,36.0,NaN,NaN
2020-12-29,2199,Mexilhão,Caparica,L5b,36.0,1.8,71.0
2020-12-29,2215,Conquilha,Culatra,L8,36.0,1.8,NaN

In [5]:
biotoxins_ts = biotoxins_ts["dsp_toxins"]
biotoxins_ts

Date
2015-01-05    20.0
2015-01-05    36.0
2015-01-05    26.0
2015-01-05    36.0
2015-01-05    36.0
              ...
2020-12-29    36.0
2020-12-29    36.0
2020-12-29    36.0
2020-12-29    36.0
2020-12-29    36.0
Name: dsp_toxins, Length: 13719, dtype: float64

In [6]:
biotoxins_ts.to_csv(data_dir + 'automts_bio_dsp.csv')